### ISSUE TITLE
Callable trait?

### ISSUE THREAD

**Issue by malmaud** [mauro3/Traits.jl#16]
I love this package!

I was wondering if it would make sense to have a common trait corresponding to whether a type ``T`` is 'callable', in the sense that if ``isa(x, T)`` then ``x(args...)`` will work.

**Comment by mauro3** [comment]
Tnx!  Yes, that does make sense.  To be callable this should work:
```julia
@traitdef IsCallable{X} begin
    @constraints begin
        X==Function || length(methods(call, (A,)))>0
    end
end
```
or are there other cases?

**Comment by malmaud** [comment]
I think that should do it.

**Comment by mauro3** [comment]
Cool, I'll probably put that into https://github.com/mauro3/SimpleTraits.jl/blob/master/src/base-traits.jl.

**Comment by mauro3** [comment]
Closed in favor of https://github.com/mauro3/SimpleTraits.jl/issues/1
