### ISSUE TITLE
Move method signature comparison to separate package

### ISSUE THREAD

**Issue by mauro3** [mauro3/Traits.jl#20]
If method comparison becomes its own package, then https://github.com/Rory-Finnegan/Interfaces.jl could make use of it.  This would mostly concern the function `isfitting`.

**Comment by mauro3** [comment]
Cc: @Rory-Finnegan

**Comment by tonyhffong** [comment]
+1 provided that the strictness and scoring (when non-strict) requirements do line up

**Comment by mauro3** [comment]
Sorry, I should have been more detailed as I think you're referring to dispatch of trait-functions. This is about matching method signatures in the traitdef against defined methods.
